# Generated by Django 6.0.4 on 2026-04-09 16:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('mood', models.CharField(choices=[('vexed', 'Vexed'), ('stressed', 'Stressed'), ('tired', 'Tired'), ('broken', 'Broken'), ('calm', 'Calm')], default='stressed', max_length=20)),
                ('category', models.CharField(choices=[('traffic', 'Traffic Wahala'), ('work', 'Work Drama'), ('sapa', 'Sapa'), ('health', 'Health'), ('chaos', 'General Chaos')], default='chaos', max_length=20)),
                ('tension_level', models.IntegerField(default=50, help_text='1 is chill, 100 is pure shege', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
